version: "3.8"

services:
  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # Prevents overriding node_modules inside container
      - ./frontend:/app:delegated  # Syncs frontend files
    environment:
      - REACT_APP_API_URL=http://localhost:5251
      - NODE_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - planaid-network

  backend:
    build: 
      context: ./backend
      target: development
    ports:
      - "5251:5251"
    volumes:
      - ./backend:/src
      - dotnet-cache:/root/.nuget/packages
      - backend-obj:/src/obj
      - backend-bin:/src/bin
      - ./metrics/backend:/app/metrics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PythonServiceUrl=http://python_service:8000
      - ASPNETCORE_URLS=http://+:5251
      - NerServiceUrl=http://ner_service:8001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - planaid-network

  python_service:
    build:
      context: .  
      dockerfile: python_service/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./python_service:/app/python_service
      - ./python_service/app:/app/app
      - ./python_service/requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
      - ./metrics/python_service:/app/metrics
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - planaid-network

  ner_service:
    build:
      context: ./ner_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ner_service:/app
      - ./logs/ner_service:/app/logs
    environment:
      - LOG_LEVEL=DEBUG
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - planaid-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - planaid-network

volumes:
  dotnet-cache:
  backend-obj:
  backend-bin:
  redis-data:
  ner-models:
  metrics_data:
    driver: local

networks:
  planaid-network:
    driver: bridge