name: CI Pipeline

on:
    push:
        branches:
            - main
            - dev
            - are
            - simen
            - ole
            - feature/*
    pull_request:
        branches:
            - main
            - dev

jobs:
    backend:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore PlanAid.sln

            - name: Build application
              run: dotnet build PlanAid.sln --no-restore

            - name: Run tests
              run: dotnet test PlanAid.sln --no-restore --verbosity normal

    frontend:
        runs-on: ubuntu-latest
        
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
                cache: 'npm'
                cache-dependency-path: './frontend/package-lock.json'

            - name: Install dependencies
              run: npm ci

            - name: Build frontend
              run: npm run build

            - name: Run tests
              run: npm test -- --watchAll=false
